# Generated by Django 5.0.7 on 2024-07-23 21:06

import wagtail.contrib.table_block.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_hero_text_remove_homepage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepage',
            name='table',
            field=wagtail.fields.StreamField([('table', wagtail.contrib.table_block.blocks.TableBlock(non_nullable=False))], blank=True),
        ),
    ]
