# Generated by Django 5.0.7 on 2024-07-25 21:42

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_complexcontentpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablepage',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='tablepage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], default={}),
        ),
        migrations.DeleteModel(
            name='ComplexContentPage',
        ),
        migrations.DeleteModel(
            name='TablePage',
        ),
    ]
