# Generated by Django 5.0.7 on 2024-07-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_tablepage_main_img_remove_tablepage_page_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentPage',
        ),
    ]
